version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - application.py
    - requirements.txt
    - Procfile
    - templates/home.html
    - templates/index.html
    - src/pipeline/predict_pipeline.py
    - artifacts/model.pkl
    - artifacts/preprocessor.pkl
  discard-paths: no
